### ISSUE TITLE
GenericTypeReflector doesn't exist in orbit-rest-client.jar

### ISSUE THREAD

**Issue by utkusonmez** [orbit/orbit-rest-client#1]
Hi, i am trying your sample code for rest client. But i got an exception which i pasted below. It seems orbit-rest-client jar doesn't contain 'cloud/orbit/rest/shaded/com/googlecode/gentyref' package inside. I builded application with maven and also add dependency definition.

> <dependency>
>             <groupId>cloud.orbit</groupId>
>             <artifactId>orbit-rest-client</artifactId>
>             <version>0.8.1</version>
>         </dependency>
> 
> Caused by: java.lang.NoClassDefFoundError: cloud/orbit/rest/shaded/com/googlecode/gentyref/GenericTypeReflector
>         at cloud.orbit.rest.async.RestClient.getActualType(RestClient.java:438)
>         at cloud.orbit.rest.async.RestClient.invokeInternal(RestClient.java:259)
>         at cloud.orbit.rest.async.RestClient.invoke(RestClient.java:240)
>         at cloud.orbit.rest.async.RestClient.lambda$get$0(RestClient.java:210)
>         at com.sun.proxy.$Proxy12.getHome(Unknown Source)
>         at com.example.DemoApplication.main(DemoApplication.java:32)
>         ... 6 more
> Caused by: java.lang.ClassNotFoundException: cloud.orbit.rest.shaded.com.googlecode.gentyref.GenericTypeReflector
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178)
>         at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         ... 12 more

Have a nice day
Utku

**Comment by JoeHegarty** [comment]
I see the problem. I'll fix it and push out a release later today.
Thanks for the report!

**Comment by JoeHegarty** [comment]
This is resolved in 0.8.2!

https://github.com/orbit/orbit-rest-client/releases/tag/v0.8.2

Thanks for reporting the issue.

**Comment by utkusonmez** [comment]
Thanks for solving problem really fast :)
